services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: track
    volumes:
      - ./.docker/postgres/data:/data/postgres
    restart: always
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5433:5432